### ISSUE TITLE
Add On Not Loading

### ISSUE THREAD

**Issue by Reiinn** [I-A-C/plugin.video.exodusredux#10]
Here's my logs: http://paste.kodi.tv/faseqigoxi
I'm from Reddit. Basically, I click something such as "New Movies" and the circle appears and disappears. Nothing else happens.

**Comment by JonnyGadd** [comment]
Try clearing cache within the app, works fine here

**Comment by doko-desuka** [comment]
The error is this:  
`18:50:44.636 T:18446744072491860048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.exodusredux/?action=movieWidget) failed`  

I think the New Movies menu gets a fresh list from the web.  
Is your internet connection working? Can you watch anything in this same add-on but through the other menus?

**Comment by Reiinn** [comment]
I got it working, clearing cache worked fine. Thanks for the help.
