### ISSUE TITLE
RLSBB and 2DLL sources. 

### ISSUE THREAD

**Issue by JFG90** [I-A-C/plugin.video.exodusredux#12]
Hi there it appears there are problems getting RLSBB and 2DLL sources with Real Debrid, currently RLSBB are returning no links and neither is 2DLL, I'm only mainly getting 300mb film links and DirectDL providers, not sure if the scraper could be updated? This is currently using exodus redux I have tried other addons also, and heard other reports, last night 2DLL would sometimes return links but would have to scrape it at least 4 times to get the results, my timer is set to 60, clearerd all providers etc, this morning it's no returning links at all for that source along with RLSBB. Thanks in advance!

**Comment by JonnyGadd** [comment]
Appears 2DLL is working apologies, but it doesn't always scrape the links.

**Comment by JonnyGadd** [comment]
Tv shows as an example big bang theory and young sheldon would return tons of 1080, currently they atr
