### ISSUE TITLE
Quick Icon I made 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#2]
Please upload / replace as needed in plugin.video.exodusredux  and the artwork modules default theme . as needed , if you want

it was a quick job , I want to work on a new icon / fanart / background using the same kinda style / theme (movie poster backdrop ) . If i ever get around to it 

https://i.imgur.com/6hVz7Ry.png

**Comment by I-A-C** [comment]
I like it.  Graphics stuff is not my thing.  
Can you do a pull request request?

**Comment by I-A-C** [comment]
nevermind I got it
