### ISSUE TITLE
Can anything be done about this? link almost plays but doesn't? 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#21]
I've personally constantly dealt with this issue. anything can be done about it on the addon side? the link will half load and alllllmost play. I've gotten this issue for the past few months 

https://www.reddit.com/r/Addons4Kodi/comments/9y57ax/dead_link_handling_in_addons/

**Comment by SerpentDrago** [comment]
I have no idea why its showing reference above , completely unrelated issue

**Comment by 13Clowns** [comment]
you are correct no idea how it went to reference 21.
