### ISSUE TITLE
can't disable fanart

### ISSUE THREAD

**Issue by sergio49650** [I-A-C/plugin.video.exodusredux#23]
In Tools-> General, I can"t disable fanart. I uncheck fanart option , do Ok. When I come back Fanart is active.
I only managed to change it directly in userdata/addons/exodus/setings.xml

I tested it on windows, I didn't check it on my Rpi, but it should be the same

Anyway, thanks for your work ! :)

**Comment by 13Clowns** [comment]
Just tested cant reproduce. 
Setting file is setup correctly 
``<setting id="fanart" type="bool" label="32318" default="false" />``
Referencing user setting properly
``<setting id="fanart" value="false" />``

Windows/Android.

**Comment by jewbmx** [comment]
This a kodi 18 issue? I cant get it to happen for me either lol. I know my addons artwork/themes dont work on 18

So if ExoRedux is the same it might be that causin it since the used stock fanarts in the artwork module
