### ISSUE TITLE
Extended Info , Not working with TV shows 

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#3]
Windows 10 x64 / Kodi 18 / Skin Aura Leia branch

When using Extended Info as default Info Provider (skin setting in aura , and others ) 

It pulls up a blank page when going to information on any TVshow  Widget or Directly from addon . 
It should be noted Movies work fine both on widgets and directly from addon 

It seems to work perfectly fine for TVshows in other addons . (though i have not tested other Exodus based addons ) Which is why i file this as a bug under Exodus Redux . 

Would need Confirmation from someone else .

**Comment by Tikipeter** [comment]
Go to script.module.exodusredux/lib.resources/lib/indexers/tvshows.py.
Add this line at around 1072 (where there are a few lines updating the meta) and see if it works:
    
    meta.update({'imdbnumber': imdb, 'tvshowtitle': systitle})
Let us know if it fixes the issue.

**Comment by SerpentDrago** [comment]
It works ! thanks , tested and retested . 

Side note , this is going to sound really dumb .. but mybee you can help . I've finally figured out why i'm getting indent issues when trying to edit code (using notepad++ / or whatever , on Windows )  If i use tab to indent it errors , but if i space space etc. my way indent it works fine !  WTF is causing this , wouldn't' tab be the more correct way to make a indent and why does it matter ! . sorry if this is suck a noob question

**Comment by Tikipeter** [comment]
Im pretty sure Kodi python much prefers spaces to tab when indenting. Usually it doesn't matter as long as you are consistent within a module, but with Kodi python coding it's best to stick with spaces.
I use Sublime Text on Windows, and there is a menu option to use spaces when you indent using the tab button. There's probably a similar setting in notepad++.
