### ISSUE TITLE
Exodus Redux not syncing with Trakt

### ISSUE THREAD

**Issue by thequeeng** [I-A-C/plugin.video.exodusredux#5]
I am having issues with Exodus Redux not marking Trakt episodes as watched, can you recommend a solution?

**Comment by SerpentDrago** [comment]
do you have the Trakt addon installed and auth'd ? its in the official kodi repo

**Comment by thequeeng** [comment]
Yes I do.

**Comment by thequeeng** [comment]
I have resolved this issue. 

Re-authorised the trakt app (not Exodus Redux) and made sure that the settings in Exodus Redux was set to mark episodes as watched in the scrobbler settings!

**Comment by thequeeng** [comment]
Update - now the tv “collection” list won’t open

**Comment by 13Clowns** [comment]
Reauthorize trakt. No issues with current module update

**Comment by thequeeng** [comment]
Tried it. Tried clearing cache, too. Not scrobbling correctly or showing the collection.

**Comment by thequeeng** [comment]
Even rebooted the box. 

Mat try uninstalling and re-installing the addon tomorrow.

**Comment by 13Clowns** [comment]
Also add this to advance.xml

```
<video>
	<playcountminimumpercent>90</playcountminimumpercent>
	<ignoresecondsatstart>180</ignoresecondsatstart>
	<ignorepercentatend>5</ignorepercentatend>
</video>
```
