### ISSUE TITLE
Rebrand of ExodusRedux and Lambada Scrapers

### ISSUE THREAD

**Issue by SerpentDrago** [I-A-C/plugin.video.exodusredux#6]
I feel a Rebrand of ExodusRedux and Lambada Scrapers is in order . 

I say We call it     

Moses  &   The Tablets of Stone

/s only slightly

**Comment by SerpentDrago** [comment]
Or ,     Leviticus and The Rituals

**Comment by JonnyGadd** [comment]
This definitely sounds good, maybe change the artwork for it to :)

**Comment by drinfernoo** [comment]
Definitely would need new artwork in the event of a rebrand.

**Comment by drinfernoo** [comment]
> Or , Leviticus and The Rituals

Leviticus was my idea, for the record 😂

**Comment by SerpentDrago** [comment]
The Rituals my add :)
