### ISSUE TITLE
Requested setting for scraper

### ISSUE THREAD

**Issue by JFG90** [I-A-C/plugin.video.exodusredux#9]
Would it be possible to add a feature that enables us to remove the bottom line that says normal 1080p 720 SD in the box that we see when it's scraping for links? It would be a pretty cool feature for us RD users so that when we click on a movie or tv show the box only displays the top line that usually says Prem : 1080 etc. Hope this makes sense 🤣

**Comment by jewbmx** [comment]
Shouldnt be hard since the setting to hide results from the list is there, could code it to check if that settings enabled when the search starts and set it up like the setup for paid to show when rd is enabled lol.

Does anyone ever see free results for stuff come out before paid tho?
